### ISSUE TITLE
Object/Schema Definitions

### ISSUE THREAD

**Issue by timkleier** [Significant-Gravitas/AutoGPT#6751]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Beyond storing prompts, we could store structured domain and/or application instructions in JSON/YAML. The architect and/or tech lead agent would request structured output from the LLM and store it in the database, then use that to generate models, API endpoints, and/or UI code.

One potential format is [DNA Codes](https://github.com/upgrade-solutions/dna/wiki), a project I'm working on that defines a set of _portable, language-agnostic, structured set of instructions_ for building software.

### Examples 🌈

An example of a set of instructions for blog post objects:
```yaml
Objects:
  Article:
    Title: String!
    DatePublished: Date
    Published: Boolean
    Authors: [Author]
    Comment: [Comment]
  Author:
    Name: String!
    ImageUrl: String
  Comment:
    Body: String
    UserId: Integer
    Timestamp: DateTime
```

### Motivation 🔦

Results with human language prompts can be unpredictable, so we need a structured specification for application creation and updating.
